### ISSUE TITLE
"X" on Edit Pages Doesn't Have Rollover Help

### ISSUE THREAD

**Issue by JEGeyer** [HPDCollaborative/builder-ui-beta-reporting#1]
The "X" on edit pages doesn't currently have rollover help.  It's fairly obvious, but I hesitated the first time I clicked on it, and since the ? has help I'm thinking we should add something.  I suggest: "Close form without saving"

**Comment by 19peaches** [comment]
Every application on the planet uses an X to close windows, I'm not really sure this is something we need to tell people. Let's see if we get any +1's from the other beta testers.

**Comment by JEGeyer** [comment]
OK, That makes sense, I'm good with waiting for other responses.

**Comment by 19peaches** [comment]
I went ahead and added this, I don't see any reason not to, it's pretty harmless.
