### ISSUE TITLE
Change "Check substance" button to "Add a substance manually"

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#11]
Change "Check substance" button on add substance screen to "Add a substance manually"

**Comment by 19peaches** [comment]
I think Add Manually should be sufficient, that's too much text for a button.

**Comment by 19peaches** [comment]
Fixed

**Comment by JEGeyer** [comment]
Confirmed this fix 8/8/18
Button says "Add Manually" and rollover help says "Add Substance Manually", I think this works well in the context of the screen.
Leaving Fixed label on so Milla can also review.

**Comment by Millali** [comment]
Yes, this works.

Milla

**Comment by JEGeyer** [comment]
Removed fixed label
