### ISSUE TITLE
How can I run a LEED Pre-check or re-screen substances?

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#12]
I was not able to find the LEED- Precheck and re-screen substances button.

**Comment by 19peaches** [comment]
Yes this needs to be determined still, my though is the bottom buttons bar.

**Comment by 19peaches** [comment]
Buttons were added to the buttons bar, they aren't wired up yet, but they are positioned and styled. Just waiting on confirmation that the layout is good to go.

**Comment by JEGeyer** [comment]
Layout is good to go.
