### ISSUE TITLE
Basic inventory records

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#14]
Hi Vince, 

I am moving this conversation to Github to have it all in one place. 

Attached a good basic record. A basic is like a nested with just 1 material. So when you select basic method a material is automatically created and it is named the same as the product name.

-This "material" can't be deleted from the HPD and no other materials can't be added to the HPD. 
- The material can be edited and is refereed as "product" in basic HPDs.  For example: instead of saying "Edit Material" it reads "Edit Product". Same with notes fields. 
- % percent and HPD URL is not reported for the product in basic inventories. Just notes and R&Is. 

Let me know if you have questions! I think that maybe is a good idea if John sends you the specs for 2.1? 

Millla
[publish_90_USG_Drywall_Suspension_System_1520538792.pdf](https://github.com/HPDCollaborative/builder-ui-beta-reporting/files/2267817/publish_90_USG_Drywall_Suspension_System_1520538792.pdf)

**Comment by 19peaches** [comment]
Cool, once we get everything else ironed out here I can add this in.
