### ISSUE TITLE
Not able to screen substance manually

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#16]
When I click "Add manually" I should be able to  select the substance from the type ahead (so that it gets screened) and also select the manual options for i.e. don't disclose the CAS number of the substance.  Right now if I select the substance from the type ahead the "Add manually" options go away.

**Comment by 19peaches** [comment]
You're going to have to show me what you mean in a live demo, I pretty much duplicated exactly what the current builder does as far as I'm aware.

**Comment by 19peaches** [comment]
If you select the substance from the typeahead, there's nothing to add manually, the substance is pulled in from pharos and then you simply fill in the percentages, role etc. as normal. The substance is screened when you save the substance. This works the same way in the live builder, when you click on a substance from the typeahead, you aren't allowed to access the manual options.

If the substance isn't found in the typeahead you click the add manually button and you enter the details manually, this is no different than the current builder.

I guess I'm not understanding what you think is different.

**Comment by Millali** [comment]
Hi Vince, 

No, this is not the way it works now and users indeed need the manual options to select non-diclosure or edit the substance name. If you notice,  the type ahead (search box) is placed in two places in the Builder. One in the add a substance screen and also in the manual substance entry screen. See:

https://builder.hpd-collaborative.org/v21/records/6023/materials/8733/substance/create-manual

This is the only way for supplier to enter proprietary information and for consultants to mark substances as 3rd party screened. We need to work exactly as the Builder works now. 

Thanks, 

Milla

**Comment by 19peaches** [comment]
The way it works now is wrong in that it allows users to save substances with nothing but a name and/or pharos_id (coming from the typeahead), hence the reason it's been changed.

There is no need for a typehead here, in the current builder, the typahead is the exact same one that appears initially, why would it be found the second time if it wasn't found the first time? 

We can easily set it up to screen by CAS number once it's saved for manual ones as well, but the typeahead isn't needed, they just enter the CAS number. Perhaps you'll need to demo and explain as I said originally, but I won't allow the database to continue to get worse by adding substances without the correct data attached as the builder does now. 

This is one of the reasons the db is so screwed up now.

**Comment by 19peaches** [comment]
![screen shot 2018-08-16 at 10 03 10 am](https://user-images.githubusercontent.com/1456472/44223170-ac42c700-a13b-11e8-9aa9-a1cd168c7135.png)

As you can see here, I entered a name manually, entered the CAS number for DIETHYLENE GLYCOL DIMETHYL ETHER, filled out the rest of the form, then clicked Save Substance, and you can see everything was saved, the substance was scanned, I didn't select do not disclose, or third party but they are both on the form.

**Comment by Millali** [comment]
Hi Vince, 

I will demo in our meeting tomorrow. Before making decisions about removing functionality in the Builder I really think is better to discuss it first so we avoid this type of issues. The way is working now is correct because it is the only way a supplier or a consultant can add a substance without disclosing the name and CAS number of the substance to other users in the same Builder account. It is critical that the CAS and name can be hidden once the substance has been added and right now I am not able to do it. I can only hide them in the pdf but I  need to be able to hide them in both the pdf and the Builder if I want to. 

Please read my first email carefully, I am not asking for another search box to get added, I am asking for  the manual options (specially the check boxes) to stay active when I select the substance from the type ahead and I had selected enter manually. 



Milla

**Comment by 19peaches** [comment]
this is fixed, pushing shortly
