### ISSUE TITLE
Product and company name missing in the header

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#17]
Hi Vince, 
 Wendy noticed that the product and company names are missing in the Builder header. It is important to add the name of the product and manufacturer back as it displays now in the current Builder. Please see the attached ppt with a sketch on how we want think should look but we are open to any suggestions if this doesn't work. 

Thanks!

Milla
[Product_Manufacturer_name.pptx](https://github.com/HPDCollaborative/builder-ui-beta-reporting/files/2294281/Product_Manufacturer_name.pptx)

**Comment by 19peaches** [comment]
I can't do anything with that file, please upload a non-propriatary file type such as a PDF.

Thanks

**Comment by Millali** [comment]
pdf attached.

[Product_Manufacturer_name.pdf](https://github.com/HPDCollaborative/builder-ui-beta-reporting/files/2294623/Product_Manufacturer_name.pdf)

**Comment by 19peaches** [comment]
that looks very dumb and 1996 but ok ...

**Comment by 19peaches** [comment]
John and discussed adding this to the main orange headers instead so we can start moving away from that horrible looking long huge block text.  I'll upload a screen in a moment.

**Comment by 19peaches** [comment]
![screen shot 2018-08-16 at 3 18 00 pm](https://user-images.githubusercontent.com/1456472/44238278-db236200-a168-11e8-8b3d-99b30ad6d7d0.png)

We're gonna go with this instead of the old stodgy block text, much cleaner and better for forward development.
