### ISSUE TITLE
Text update in forms

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#18]
Hi Vince, 

Would you please edit the forms top text as indicated below?

Product Form   --> Add/edit Product
Material --> Add/edit Material
Substance Form --> Add/edit Substance
Certification Form --> Add/edit Certification
Accessory Form --> Add/edit Accessory

Thanks!

Milla

**Comment by 19peaches** [comment]
very well

**Comment by 19peaches** [comment]
There is no place for this in the Product form

**Comment by Millali** [comment]
Thanks fine. No need to add. thanks!
