### ISSUE TITLE
Sections text update

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#20]
Hi Vince, 

Attached a pdf with the new text for the sections. Please let me know if you have questions! @JEGeyer feel free to review once again and provide your feedback. 

Thanks!
[Navigation text_.pdf](https://github.com/HPDCollaborative/builder-ui-beta-reporting/files/2295358/Navigation.text_.pdf)

**Comment by 19peaches** [comment]
pushed
