### ISSUE TITLE
Instruction panel

### ISSUE THREAD

**Issue by Elixir-Tara** [HPDCollaborative/builder-ui-beta-reporting#22]
Can't get instruction panel to open from any of the sections.

**Comment by JEGeyer** [comment]
Hi Tara, Thanks for getting started on this so quickly!
I wasn't able to reproduce this problem, can you tell us what browser you're using?

**Comment by 19peaches** [comment]
Please report your operating system with version, and your browser and version, this sounds like it's probably a browser related issue.

Thanks Tara

**Comment by Elixir-Tara** [comment]
Yep. Works in Safari. Another one for the Firefox pile!
