### ISSUE TITLE
Nested not working

### ISSUE THREAD

**Issue by Elixir-Tara** [HPDCollaborative/builder-ui-beta-reporting#24]
Can't do anything in nested display. No data boxes show up.

**Comment by 19peaches** [comment]
Please report your operating system with version, and your browser and version, this sounds like it's probably a browser related issue.

Thanks Tara

**Comment by Elixir-Tara** [comment]
OS X El Capitan, Firefox 61.0.2.

And thank you for your help!!!

**Comment by JEGeyer** [comment]
I just looked at this as well, and when I created a new nested record I had the same experience.  None of the forms are displaying -- just the button bar at the bottom of the screen.  I'm using Chrome 68 on Windows 10.
A new basic record worked as expected...

**Comment by Elixir-Tara** [comment]
Nested not working on Safari either.

**Comment by 19peaches** [comment]
This is related to the issue we discussed in the meeting with the function that renders the header method/threshold.

Lets try and slow down on creating new HPD's until the bug fixes we discussed this morning are handled please.

Thanks.

**Comment by 19peaches** [comment]
this is resolved in the latest push.
