### ISSUE TITLE
Buttons Bar and Other Elements Not Rendered in Firefox

### ISSUE THREAD

**Issue by Elixir-Tara** [HPDCollaborative/builder-ui-beta-reporting#26]

**Comment by 19peaches** [comment]
Rescreen is in the buttons bar at the bottom

**Comment by Elixir-Tara** [comment]
Not on my account (see screenshot):
![screen shot 2018-08-17 at 4 54 07 pm](https://user-images.githubusercontent.com/42480000/44293153-468b3380-a23e-11e8-8c70-ef834e554507.png)

**Comment by 19peaches** [comment]
Tara can you try this in Safari and see if it works, I've tested in both Chrome and Safari and it works fine.

The builder is deveoped using the Webkit engine and Node JS which is part of the Chrome javascript engine, best results will always be in a Webkit based browser such as Chrome, Safari, Brave. etc.

**Comment by Elixir-Tara** [comment]
Yes, the rescreen button shows up in Safari.

**Comment by 19peaches** [comment]
@Elixir-Tara All these button issues should be resolved in FF with the latest push, except for the instructions panel ... still researching.

**Comment by 19peaches** [comment]
@Elixir-Tara 

Hi Tara, can you please revert back to Firefox now and test all the issues you had before, I believe they are all resolved.

I'm going to close this, if new errors arise please open a fresh ticket.

Thanks.

V

**Comment by Elixir-Tara** [comment]
It does seem that all of the problems with Firefox have been resolved. Thank you!
