### ISSUE TITLE
Content Inventory (Nested)

### ISSUE THREAD

**Issue by ddavis715** [HPDCollaborative/builder-ui-beta-reporting#29]
Can a disclaimer/note be added that you add substances/ingredients in a different section? I spent a few minutes on the Materials page looking where to add the nested ingredients.

**Comment by 19peaches** [comment]
I'll leave this open for further input from other beta users, but I think an entire section called Substances explains it pretty well.

Also, there will be a tour that we're working on that will highlight new sections, and other points of interest such as the buttons bar and the instructions panel.

**Comment by Elixir-Tara** [comment]
The way that the nested inventory is set up now is a bit confusing wrt materials/substances. It seems that there should be more "at a glance" information available (without having to click to edit each material/substance), and more connection between the materials and their substances. With the current version of the Builder, you can see the hierarchy of contents. With this new layout, it's much less intuitive. If we're going this route, perhaps we could include, e.g. percent, role, etc. in the overview... and perhaps be able to click on the material name to see the nested substances. My preference would be to completely combine the materials and substances into a single tab, but I'm not sure how that would work with the current coding.

**Comment by 19peaches** [comment]
@Elixir-Tara 

Some of this may be doable, though there is lack of available space in the current material rows, though I'm completely open to changing what data shows, I have no clue what's most useful.

Combining materials and substances is exactly what we DON'T want. They are completely separate entities and are (mostly) reusable, thus they should never have been displayed together in the first place. The idea is to understand that a substance isn't nested (programmatically) to a given material and as such allows the materials to be reused.

As the standard moves forward, it's my understanding there will be even another level of hierarchy that will need to be implemented, (I believe it will be called a "part" or "assembly") so getting users used to this type of format now, sets us and you, up for success as we moving forward.

**Comment by 19peaches** [comment]
Closing
