### ISSUE TITLE
LEED pre-check

### ISSUE THREAD

**Issue by ddavis715** [HPDCollaborative/builder-ui-beta-reporting#30]
Where is the LEED pre-check located?

**Comment by ddavis715** [comment]
I did find this in the Contact and Publication section. This does not seem like an intuitive location in my opinion

**Comment by JEGeyer** [comment]
We put it here because the rest of the HPD needs to be complete to pass the LEED pre-check, and we thought it made sense to have it at the end of the HPD and just before you publish.

**Comment by 19peaches** [comment]
As @JEGeyer said its with the Publish functionality.

While we appreciate your opinion, perhaps it would be more helpful if you offered some sort of feedback on what you think might be a better solution so it can be discussed.

**Comment by ddavis715** [comment]
I guess i'm just used to it being in the Materials/Substance section.  I'm sure the your you mentioned in a previous response will direct people there.
