### ISSUE TITLE
Nested w/ Product Threshold

### ISSUE THREAD

**Issue by Elixir-Tara** [HPDCollaborative/builder-ui-beta-reporting#31]
Being prompted to select threshold for each material. Should be a single product threshold for all materials.

**Comment by 19peaches** [comment]
I'll let @Millali and @JEGeyer weigh in on this, but it's my understanding that documenting individual thresholds per material is one of the advantages of a nested inventory type.

The current builder also allows this functionality.

**Comment by JEGeyer** [comment]
That's true of Nested/Material inventories, but with the Product level threshold the materials/substances are added (or not) based on their weight % for the whole product, not for each material. So Tara is right, when the product threshold is set, users should not be prompted at the material level and the threshold applies across all materials/substances.

**Comment by 19peaches** [comment]
Ok I'll have to research how to fix this.

Not sure how this wasn't caught much earlier, materials were one of the first pieces completed.

**Comment by 19peaches** [comment]
@Elixir-Tara @JEGeyer this is now fixed in the latest push. New material form threshold is taken directly from the detail threshold_type IF that type IS NOT "Material".

That should resolve it, it's not visible to the user, but still validates successfully.

**Comment by Elixir-Tara** [comment]
Looks great, thanks!
