### ISSUE TITLE
Not able to save substances w/o registered identifier

### ISSUE THREAD

**Issue by Elixir-Tara** [HPDCollaborative/builder-ui-beta-reporting#32]
I'm not able to save substances that don't have a CASRN. They show up in the drop down menu (e.g. wood, mixed recycled paper), but they won't save.

**Comment by 19peaches** [comment]
Please detail the steps to reproduce the error as per the read me.

Thanks

**Comment by Elixir-Tara** [comment]
1. (In Basic, or in Nested with at least 1 material already added) Click "Substances" tab
2. Click "Add Substance" tab
3. Type "Paper" in box. Select "mixed recycled paper" or "kraft paper" from drop down menu.
4. On "Add/Edit Substances" screen, fill in required info (%, role, recycled content, notes)
5. Click "Save Substance" - on my computer (tried Firefox and Safari) nothing happens.

**Comment by 19peaches** [comment]
@Elixir-Tara this should be resolved, please check on your end.

**Comment by Elixir-Tara** [comment]
That did it... Thanks!
