### ISSUE TITLE
Can't jump to other sections on IE

### ISSUE THREAD

**Issue by luke88zz** [HPDCollaborative/builder-ui-beta-reporting#35]
**Describe the bug**
I can't jump to other sections of the builder on IE, but it works on Chrome. 

**To Reproduce**
1. Log onto the builder on an IE browser. 
2. After creating the product entry, click on other sections that you want to work on
3. See error

**Expected behavior**
The page won't jump to the sections that you click on.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [IE]

**Comment by 19peaches** [comment]
@luke88zz 

Can you tell me what version of IE you're using please?

**Comment by luke88zz** [comment]
Hi Vince,

It’s IE 11. Below is the screenshot:

[cid:image002.png@01D43A2A.D37AE0F0]

**Comment by 19peaches** [comment]
@luke88zz 

Screenshots won't work when replying by email, you'll need to come up to GitHub and drop it here.

Thanks

**Comment by 19peaches** [comment]
@luke88zz 

Currently Windows 11 doesn't support ES6 completely, specifically Promises which are used in the application to ensure that one process completes before the next one begins.

I have checked it out in Edge and it does work fairly well. I would still recommend using Chrome or Safari or even Brave, these are all Webkit based browsers and will give you the best experience.

Let me know if you have any more questions.
