### ISSUE TITLE
Product Section of HPD - allows to save with * info entered

### ISSUE THREAD

**Issue by paviaedward** [HPDCollaborative/builder-ui-beta-reporting#37]
I don't know if this is still under development, but when there is a text box that has an * next to it that means that the info is required - so on the old format if you tried to save that specific screen info without entering the verbiage for the * marked box, the program would tell you you have to enter the info  and would not allow you to save the info - under the new format, I am able to save the info and move along without it telling me that required areas are not completed.

**Comment by 19peaches** [comment]
Please use the Bug report form to detail these areas as requested. We can't fix them if we can''t duplicate the problem.

**Comment by 19peaches** [comment]
@paviaedward 

Please advise.
