### ISSUE TITLE
how to see the full substance list with all info

### ISSUE THREAD

**Issue by paviaedward** [HPDCollaborative/builder-ui-beta-reporting#38]
Once I have entered in all my substances and info, is there a way to then view all of the them and all of their info like we could on the old version (CAS#, %, role, notes) - right now I only see the listing of the name of the substance after I enter it, and do not see all of its info unless I click on the "view hazards" button - and even then, I don't see what % the substance is listed at....?  This just makes it difficult for others to review and QC as now they have to click on every substance just to see its info, instead of having a list of all the substance that you can scroll down on and see all their info.  I am not seeing anywhere where it lists what the % of the chemical is after I have entered it in...?

**Comment by 19peaches** [comment]
Feedback on what to show per each substance row in the table is greatly welcomed and encouraged, as for seeing it all in the old format ... no that's part of the reason it's been changed so as to remove that long tedious scrolling document to a more modern and concise UI to build the HPD.

You can always Preview your HPD as you go to ensure that you've added all the sections correctly. Of course that's what the Completeness Check is for, to ensure you've completed everything that's needed.

**Comment by paviaedward** [comment]
Hello Vince – yes! – the preview function – that is what I was looking for – that works well…than you for your comment on that.

Thank you!

Edward Pavia, M.S.
Senior Project Manager
ToxServices LLC
1367 Connecticut Ave. NW, Suite 300
Washington, DC 20036

202-429-8795 (office)
202-429-8788 (fax)

**Comment by 19peaches** [comment]
Glad I could help.

Just a little trick Edward, the Preview opens in a new window, so you can simply keep that window open, then refresh to update it once you've made significant changes to your HPD.
