### ISSUE TITLE
How will people see Substance info if the HPD is printed out

### ISSUE THREAD

**Issue by paviaedward** [HPDCollaborative/builder-ui-beta-reporting#39]
Right now I have noticed that you have to click on extra buttons to see the additional substance info (hazards...) - if the HPD is printed out (hard-copy), how will the reader of the HPD see the additional info for the substance? - right now it only looks like they will just see the name of the substance (and no %, function, role, notes or hazards) - all of those can only be accessed digitally....am I missing a separate function that puts all on one screen?

**Comment by 19peaches** [comment]
The HPD format remains unchanged as you can see by rendering a Preview of your HPD, we have simply changed the UI for building the HPD to modernize the workflow, and to prepare for future advancements to the Builder.
