### ISSUE TITLE
Opening existing HPD

### ISSUE THREAD

**Issue by lisabritton** [HPDCollaborative/builder-ui-beta-reporting#40]
**Describe the bug**
I clicked on an existing HPD and got the following error messages:

at HandleExceptions->handleError(8, 'Undefined variable: newMaterial', '/home/forge/staging.hpd-collaborative.org/app/Http/Controllers/Product/RecordController.php', 412, array('recordId' => '816', 'request' => object(Request), 'record' => object(Record), 'newRecord' => object(Record), 'material' => object(Material), 'pivotData' => array('material_id' => 396, 'substance_id' => 28103, 'mask' => 0, 'min' => '100.0000', 'max' => '100.0000', 'residual' => 0, 'recycle' => 'Both', 'nano' => 0, 'role' => 'Extruded Aluminum Blades', 'notes' => 'Potential residuals for the aluminum extrusions include pre-wash and pre-treat chemicals that ensure paint adhesion. The maximum amount of residual material was considered and is less than 1000ppm. Residuals present at 100ppm would be encapsulated in cured finish. Aluminum extrusions include both pre-and post-consumer recycled content as well as virgin material. Amounts of each vary by lot.', 'updated_at' => '2018-08-24 16:34:52', 'created_at' => '2018-08-24 16:34:52'), 'substance' =>object(Substance), 'newSubstance' => object(Substance)))in RecordController.php line 412
--
at RecordController->clone('816', object(Request))
at call_user_func_array(array(object(RecordController), 'clone'), array('record' => '816', object(Request)))in Controller.php line 54
at Controller->callAction('clone', array('record' => '816', object(Request)))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(RecordController), 'clone')in Route.php line 212
at Route->runController()in Route.php line 169
at Route->run()in Router.php line 658
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AllowAccess.php line 46
at AllowAccess->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 67
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 660
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 635
at Router->runRoute(object(Request), object(Route))in Router.php line 601
at Router->dispatchToRoute(object(Request))in Router.php line 590
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 53

**To Reproduce**
1. Go to dashboard.
2. Click on existing product.
3. See error

**Expected behavior**
A page of errors came up.

**Screenshots**
My screenshot won't paste, sorry.  I can email separately.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Comment by lisabritton** [comment]
My apologies, that happened when I hit, "upgrade to 2.1"  I'll start from scratch.

**Comment by 19peaches** [comment]
@lisabritton ah .... I was just going to say ... it looks like you hit the clone button ... but it is still a huge problem. I'll create a ticket on our system for it and update here for it as well.

Thanks Lisa

**Comment by 19peaches** [comment]
@lisabritton 

This should be resolved. Give it another clone and let me know if you're still getting an error.

Thanks.
