### ISSUE TITLE
Click on "products" and I get a permissions error

### ISSUE THREAD

**Issue by lisabritton** [HPDCollaborative/builder-ui-beta-reporting#41]
**Describe the bug**
From the build/edit record screen, I clicked on "products" to see if I could edit the product and I get an error, "No Permissions for this Resource"

**To Reproduce**
1. Go the main product page from the dashboard or the materials entry page
2. Click on 'products' on the top left.

**Expected behavior**

An error happens.  

**Screenshots**

![image](https://user-images.githubusercontent.com/42679288/44598947-640a5100-a79a-11e8-8deb-bd302e63dbe2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by 19peaches** [comment]
When you say "products" what do you mean? And what exactly shows up in the url please?

**Comment by 19peaches** [comment]
You can't email images ... you'll need to add them on Github

**Comment by 19peaches** [comment]
Also ... the record id 3415 doesn't exist. 

Ah ... ok that url is hard coded in to the demo ... no access is the proper response for that link. Let me see if I can correct that link to be dynamic ... the breadcrumbs system isn't completed as of yet.

My apologies.

**Comment by lisabritton** [comment]
No worries, I’m just trying to report the problems.  ☺

**Comment by 19peaches** [comment]
I've corrected this bug in the breadcrumb.
