### ISSUE TITLE
Unable to save a new material

### ISSUE THREAD

**Issue by lisabritton** [HPDCollaborative/builder-ui-beta-reporting#43]
**Describe the bug**
I was unable to save a new material.  There may have been a data or format issue, but the builder did not provide a specific error message.  

**To Reproduce**
1. Go to 'build/edit record'
2. Click on 'add material'
3. Populate material
3. Scroll down to 'save'

**Expected behavior**
There is no confirmation that the new material is saved.  When I hit back it goes away.  I did this several times with different information.

**Screenshots**
![image](https://user-images.githubusercontent.com/42679288/44600696-b4d07880-a79f-11e8-9fc6-e57b1e6f7a3c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 19peaches** [comment]
Hi Lisa.

Can you please verify which system you are attempting to create the material on? You've listed your desktop and your iPhone.

**Comment by lisabritton** [comment]
Sorry, it is a desktop in Windows.

I’m still having issues trying to make a new material.

**Comment by 19peaches** [comment]
@lisabritton 

Your chrome version should look something similar to this:

`Version 68.0.3440.106 (Official Build) (64-bit)`

This is the current version of Chrome for Windows. If you're using an older version please update to the latest version and give it another try.
