### ISSUE TITLE
Preview creates duplicate materials and is between 80 and 119 pages long

### ISSUE THREAD

**Issue by lisabritton** [HPDCollaborative/builder-ui-beta-reporting#44]
**Describe the bug**
I was testing the ability to hide a proprietary ingredient and so hit "preview" and the HPD preview PD was 80 pages long.  When I tried to repeat the same to be able to provide instructions to reproduce, it was 119 pages long.

URL:  https://staging.hpd-collaborative.org/actions/preview/5003/draft

**To Reproduce**
1. Go to materials entry page.
2. Click on 'preview'
3. Go to tab with preview
4.  See error

**Expected behavior**
Materials are duplicated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 68.0.3440.106 (Official Build) (64-bit)

**Additional context**

**Comment by 19peaches** [comment]
Ok clearly we have a bug in the upgrade function still.

Please cease testing till I resolve this.

Thanks.

**Comment by 19peaches** [comment]
This was resolved

**Comment by lisabritton** [comment]
Should I pick up the testing again?
