### ISSUE TITLE
Does not flag if material is not selected

### ISSUE THREAD

**Issue by NMeyer1357** [HPDCollaborative/builder-ui-beta-reporting#46]
When trying to input a new material, the site did not save the material and remained on the same page with no error message. It was determined that the page does not save if the top cell is not filled out. However, the site does not flag this error.

**Comment by 19peaches** [comment]
This cannot be addressed since the proper requested Bug Report information wasn't submitted.

**Comment by NMeyer1357** [comment]
Describe the bug
When entering a substance and do not choose a material from the drop box, the substance cannot be saved and no error message appears to resolve the issue.

To Reproduce
 Steps to reproduce the behavior:
1.Go to add substance
2.Select add substance  
3.Fill out remaining necessary field and finalize by selecting add substance
4.Error is observed as substance is not saved to edit list 

Expected behavior
 A red error field should appear to inform user to include material data from the drop down box in order to save substance to edit list. 

Screenshots
 The builder 2.1.1 is down now so unfortunately I cannot reproduce screenshots.

Desktop (please complete the following information):
•OS: Windows 10 Pro
•Chrome 64-bit Version 68.0.3440.106
•Version 1709

Additional context
 The above procedure steps 1-5 was the proper procedure for entering substance information to the manufacturer in builder v2.1

**Comment by 19peaches** [comment]
@NMeyer1357 

That control element is a custom control and we simply missed customizing the error highlighting.

Thanks, this is resolved in the next push.
