### ISSUE TITLE
Not able to register on staging Builder

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#49]
**Describe the bug**
Hi Vince, 

I tried to register as a new user on staging and I was not able to do it. I tried with 2 different email addresses. Here are the steps to reproduce:

**To Reproduce**
1. Go to 'https://staging.hpd-collaborative.org/register'
2. Fill in the required data and make sure to click the checkbox to accept terms and conditions.
3. Do the robot challenge
4. Click in register.

**Expected behavior**
I am getting a message "The selected accepted is invalid" 

**Screenshots**
Screenshot attached..

**PC
 - Chrome

Thanks!

Milla

**Comment by 19peaches** [comment]
Oh ... yeah, good catch, I added the new terms checkbox and forget the backend part .... I''m on it.

**Comment by 19peaches** [comment]
Pushed fix to staging

**Comment by Millali** [comment]
Thanks!
