### ISSUE TITLE
Change Error Message for No R&I Notes from Edit Material Form

### ISSUE THREAD

**Issue by JEGeyer** [HPDCollaborative/builder-ui-beta-reporting#5]
Currently, the error message for trying to save an edited Material without adding Residual & Impurities notes is: "Please include at least 30 characters of text for residuals/impurities".
This should be: "Please provide an explanation of whether and how residuals and impurities were or were not considered. See 2.2.1.6 in the Standard/Instructions."

**Comment by 19peaches** [comment]
No these are validation messages, not references to the standard, this would not be appropriate to reference the standard or any non-function based errors here.

**Comment by JEGeyer** [comment]
I'm not sure I understand why we wouldn't reference the standard/instructions here but, at a minimum, we need to tell them what they're missing and I don't want to alert them to the fact that we're looking for 30 characters.  We look for a minimum no. of characters because that's all we can check -- we can't tell if they've addressed the purpose of these notes, but we figure that they couldn't have done it if they have less than 30 characters.  But the no. of characters is actually meaningless to the user or to the purpose of this entry.  I also don't want to let them know that 30 characters of gibberish will allow the system to accept the entry.
I still prefer my suggestion above because it tells them what is supposed to go here, keeps this message short, and still gives them more information if they need it and are willing to open the Instructions.  I'd entertain other suggestions, but what is entered is as functional as that something is entered here.

**Comment by 19peaches** [comment]
John, this is not a "content" validation error, it's a form length validation error. Just as if we had required validation for instance, the message would say "XXX is required."

We don't have any control over the content that's placed in that field, only that it's required, and it's a minimum length, if you start trying to add this type of minutiae to our validation routine, updating this application will spin out of control. It's not our job to hold their hand, just to make sure they know what they need to fill out, the instructions provide that detail.

**Comment by JEGeyer** [comment]
Sorry, but I'm not ready to let this go yet. :-)
I talked to Milla and she feels that it's important to tell them how many characters are required, so my argument about that was specious, but I'd still like to tell them more about what's required.  How about: "Please provide R&I notes explaining whether and how residuals and impurities were or were not considered. (30 characters minimum)" 
I know we can't control what they write, just the # of characters, and I'm not suggesting that we monitor the content -- they'll still only see this if they have <30 characters, but if it's missing, or too short, I think it's helpful to remind them what is supposed to go here.

**Comment by 19peaches** [comment]
I guess I don't understand what makes this input different from all the rest? This is clearly marked as to what the content should be, as are all the rest of the inputs ... if we do this here and not do it on all the rest of the 100 or so inputs we have we've completed corrupted the validation system for no reason. 

The biggest problem I have with this is that it breaks every rule we have for validation. Validation rules are designed to be compatible with all inputs that require the same rule, reusable using the DRY (don't repeat yourself) principle. So this means hours and hours of recording and creating separate validation messages for each individual input. That seems a bit crazy and unmanageable to me.

This is now and has always been the message for this text area and I really don't see any need for it to be more than what it is. It's not the job of the builder to dictate or remind them what goes into a properly labelled input, just to make sure that what they do enter, meets the requirements of the form and database.

**Comment by JEGeyer** [comment]
OK, I give!  :-)
I admit that I was looking at this as a single issue without considering all the other messages.  Also Milla did remind me that this is what it says now in the production Builder, and she didn't have nearly the problem with it that I did... I also don't want to burn up any more time talking about it.  If anybody else has a problem with the error messages, we can address them as a whole when the time comes.  
For now, lets move on to the other things that need to be completed (publishing, LEED precheck, re-scree, etc) -- they're way more important than this...
