### ISSUE TITLE
General Notes not displaying in pdf

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#51]
**Describe the bug**
Content entered in General Notes section is not displaying in the preview pdf

**To Reproduce**
1. Go to 'https://staging.hpd-collaborative.org/actions/6419/record' 
2. Go to General Notes and see the content. You may edit the content and save again.
3. Click on "Preview" and go to preview pdf

**Expected behavior**
General notes section is empty.

**Screenshots**
NA

**Desktop (please complete the following information):**
Can we save my profile?

**Comment by 19peaches** [comment]
Fixed pushing to staging

**Comment by Millali** [comment]
thanks!
