### ISSUE TITLE
Wery long URLs wrapping material names (suggestions?)

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#52]
**Describe the bug**
Material name is wrapping when very long URLs are entered. Were we going to add a URL shortener? I am a little confused!

**To Reproduce**
1. Go to 'https://staging.hpd-collaborative.org/actions/preview/6419/draft"
2. Note how the long URL displays in the first material.

**Expected behavior**
Material name is wrapped due to the length of the HPD URL.

**Comment by 19peaches** [comment]
That won't be available until 2.1.1

**Comment by 19peaches** [comment]
Until then the user should shorten the url themselves at bitly or wherever they choose.

**Comment by Millali** [comment]
Good :) ignore then
