### ISSUE TITLE
Consultants/View & edit not able to see "Manage" button

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#56]
**Describe the bug**
Hi Vince, 

Some users are not able to see the Green button for "Manage" in their Dashboard.  I traced down a couple of accounts and noticed that this is happening to "consultants" and for "View and Edit" users. These two type of users need to have access to this functionality. 

**To Reproduce**
1. Log into the Builder with creadentials: u:millali@gmail.com p: test1234
2. Go to Dashboard
3. Notice that there is no green button for "Manage" 

**Expected behavior**
Missing manage button

**Screenshots**
Attached a screenshot of a different account, millali@sustainableminds.com 

**Chrome, windows

**Additional context**
Consultant and view and edit users need to be able to manage the records.

**Comment by 19peaches** [comment]
@Millali so the weird part .... I pulled a copy of the app from before I even started, just to make sure this wasn't something I screwed up along the way ... and theres literally no record of users having this permission. Viewing a product is specifically listed in the permission policies, meaning it must be granted ... and I don't see anyplace that it is granted even in the old code.

I'll push an update in a little bit. Still scratching my head ....
