### ISSUE TITLE
Material/Substance Data Not Showing in Production

### ISSUE THREAD

**Issue by JEGeyer** [HPDCollaborative/builder-ui-beta-reporting#57]
**Describe the bug**
The HPDC "Cushion Tile by Sustain Carpets" Record that was Published on 9/7/2018 (Record 4632) is not showing any data for Materials/Substances.  The same record in Staging is fine.
**To Reproduce**
1. Go to Record 4632/Materials
2. Scroll down to Data Display

**Expected behavior**
There should be 3 materials -- Face Yarn, Backing, Portland Cement

**Screenshots**
![image](https://user-images.githubusercontent.com/34175254/46358977-0bda3080-c61d-11e8-8358-8c0d121b404c.png)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser Chrome

**Comment by 19peaches** [comment]
reverted to backup and posted a message to the builder dashboard
