### ISSUE TITLE
Change UnScreened to Not Screened

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#58]
**Is your feature request related to a problem? Please describe.**
Hi Vince, 

Would you please change UnScreened to Not Screened in GS field both in the Builder and the pdf? UnScreened is a good term for the Builder but not for the HPD itself. 

Thanks!

**Comment by Millali** [comment]
Thanks, we actually will need to add an amendment to the HPD Open Standard just for this!

**Comment by 19peaches** [comment]
Completed
