### ISSUE TITLE
Display type of inventory on records page

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#6]
Please change (n) and (b) on record screen to (nested) and (basic). 

i.e.: HPD v2.1 (basic) Created: 07:10:2018

**Comment by 19peaches** [comment]
very well, I assumed the users were smart enough to know what these stood for, but I can change them back

**Comment by JEGeyer** [comment]
Confirmed this fix 8/8/18.
