### ISSUE TITLE
Change options text to match the standard sections

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#8]
Hi Vince, 

I need to work more on this but the options on the left on this screen: https://staging.hpd-collaborative.org/actions/4962/record, needs some adaptation to the standard language so people can relate to the requirements. The standard has 6 sections and some of the options now can be grouped under each of them. For example: 

Section 1: Summary
Details (change to: General Information)
VOC content information

Section 2: Content in Descending Order of Quantity
Move Threshold under this section. 
Materials
Substances
Section 3: Certifications and compliance
Certifications
Section 4: Accessories
Accessories
Section 5: General Notes
General Notes
Section 6: References
References  

I will also provide instructions text for each. 

Milla

**Comment by 19peaches** [comment]
Negative, these items will not fit in the tabs, thus they've been shortened and a description added to ensure there is no confusion about what gets entered in the panels.

The description can be changed, the title cannot unless it's short enough to not screw up the layout.
